<template>
  <div class="container">
    <h1 class="text-center text-uppercase mt-5 swing-in-top-fwd">
      {{ appName }}
    </h1>
    <div class="mt-5 swing-in-top-fwd">
      <currency-input
        class="form-control form-control-lg giga-input"
        v-model="mediumPrice"
        :options="config"
      />
    </div>
    <div
      v-if="mediumPrice > 0"
      class="mt-5 text-center swing-in-top-fwd"
    >
      <h2 class="my-5 text-center text-uppercase">
        Valores de venda
      </h2>
      <p
        v-for="result in results"
        :key="result.base"
        class="mt-2 font-monospace"
      >
        <span class="badge rounded-pill label-white">
          {{ result.label }}
        </span>
        {{ result.total }}
      </p>
    </div>
  </div>
</template>

<script setup>

import { computed, ref } from 'vue'

import CurrencyInput from '@/components/currency-input.vue'

const config = {
  "locale": "pt-BR",
  "currency": "BRL",
  "currencyDisplay": "symbol",
  "precision": {
    "min": 2,
    "max": 2
  },
  "hideCurrencySymbolOnFocus": true,
  "hideGroupingSeparatorOnFocus": true,
  "hideNegligibleDecimalDigitsOnFocus": false,
  "autoDecimalDigits": true,
  "valueScaling": "precision",
  "useGrouping": true,
  "accountingSign": true
}

const appName = 'Calculadora de Venda'

const steps = [
  {
    label: '5%',
    base: 5
  },
  {
    label: '6%',
    base: 6
  },
  {
    label: '7%',
    base: 7
  },
  {
    label: '8%',
    base: 8
  },
  {
    label: '9%',
    base: 9
  },
  {
    label: '10%',
    base: 10
  }
]

const mediumPrice = ref(0)

const results = computed(() => {
  return steps.map(step => {
    return {
      ...step,
      total: calculate(step.base)
    }
  })
})

const calculate = step => {
  const agio = (mediumPrice.value * step) / 100
  const value = (mediumPrice.value + agio) / 100
  return Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL'
  }).format(value)
}

</script>

<style scoped>

.giga-input {
  font-size: 64px;
  font-family: monospace;
  padding: 12px 24px;
  text-align: right;
  border: none;
}

.giga-input:focus {
  outline: none;
  /* border: 2px inset #F09819; */
  border: none;
  box-shadow: none;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-11-3 22:33:17
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation swing-in-top-fwd
 * ----------------------------------------
 */
 @-webkit-keyframes swing-in-top-fwd {
  0% {
    -webkit-transform: rotateX(-100deg);
            transform: rotateX(-100deg);
    -webkit-transform-origin: top;
            transform-origin: top;
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateX(0deg);
            transform: rotateX(0deg);
    -webkit-transform-origin: top;
            transform-origin: top;
    opacity: 1;
  }
}

@keyframes swing-in-top-fwd {
  0% {
    -webkit-transform: rotateX(-100deg);
            transform: rotateX(-100deg);
    -webkit-transform-origin: top;
            transform-origin: top;
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateX(0deg);
            transform: rotateX(0deg);
    -webkit-transform-origin: top;
            transform-origin: top;
    opacity: 1;
  }
}

.swing-in-top-fwd {
	-webkit-animation: swing-in-top-fwd 0.5s cubic-bezier(0.175, 0.885, 0.320, 1.275) both;
	        animation: swing-in-top-fwd 0.5s cubic-bezier(0.175, 0.885, 0.320, 1.275) both;
}

</style>